# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  host: localhost
  port: 5432
  pool: 10

development:
  <<: *default
  database: <%= Rails.application.credentials.development[:db][:name] %>
  username: <%= Rails.application.credentials.development[:db][:username] %>
  password: <%= Rails.application.credentials.development[:db][:password] %>

test:
  <<: *default
  database: <%= Rails.application.credentials.development[:db][:name] %>
  username: <%= Rails.application.credentials.development[:db][:username] %>
  password: <%= Rails.application.credentials.development[:db][:password] %>

production:
  adapter: postgresql
  database: <%= Rails.application.credentials.production[:db][:name] %>
  username: <%= Rails.application.credentials.production[:db][:username] %>
  password: <%= Rails.application.credentials.production[:db][:password] %>
  port: 5432
  encoding: utf8
  pool: 10
